
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'FROM ID SELECTquery : select_stmtselect_stmt : SELECT ID FROM ID'
    
_lr_action_items = {'SELECT':([0,],[3,]),'$end':([1,2,6,],[0,-1,-2,]),'ID':([3,5,],[4,6,]),'FROM':([4,],[5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'query':([0,],[1,]),'select_stmt':([0,],[2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> query","S'",1,None,None,None),
  ('query -> select_stmt','query',1,'p_query','parser.py',25),
  ('select_stmt -> SELECT ID FROM ID','select_stmt',4,'p_select_stmt','parser.py',29),
]
